In [2]:
import numpy as np

In [3]:
l=[1,2,3,4]

In [5]:
ar=np.array(l)

In [6]:
ar

array([1, 2, 3, 4])

In [7]:
type(ar)

numpy.ndarray

In [8]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [9]:
np.asarray(l)

array([1, 2, 3, 4])

In [10]:
a=[2,3,4]

In [11]:
np.asarray(a)

array([2, 3, 4])

In [12]:
n=np.matrix(l)

In [13]:
n

matrix([[1, 2, 3, 4]])

In [15]:
np.asanyarray(n)

matrix([[1, 2, 3, 4]])

In [16]:
a=np.array(l)

In [17]:
a

array([1, 2, 3, 4])

In [19]:
c=a#sollow copy

In [20]:
c

array([1, 2, 3, 4])

In [21]:
a


array([1, 2, 3, 4])

In [22]:
c[0]=100

In [23]:
c

array([100,   2,   3,   4])

In [24]:
a

array([100,   2,   3,   4])

In [25]:
d=np.copy(a)#deep copy

In [26]:
d

array([100,   2,   3,   4])

In [27]:
a

array([100,   2,   3,   4])

In [28]:
a[1]=400

In [29]:
a

array([100, 400,   3,   4])

In [30]:
d

array([100,   2,   3,   4])

In [32]:
np.fromfunction(lambda i,j : i==j,(3,3))#important

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j : i*j,(3,3))#important

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
np.fromfunction(lambda i,j : i+j,(3,3))#important

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [36]:
ite=(i*i for i in range(5))

In [38]:
np.fromiter(ite,float)

array([ 0.,  1.,  4.,  9., 16.])

In [40]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

In [41]:
np.fromstring('234 ,234',sep=' ,')

array([234., 234.])

In [42]:
l=[2,3,4,5,6]

In [44]:
ar=np.array(l)

In [46]:
ar.ndim

1

In [47]:
ar

array([2, 3, 4, 5, 6])

In [48]:
ar2=np.array([[1,2],[3,4]])

In [49]:
ar2.ndim

2

In [50]:
ar.size

5

In [51]:
ar2.size

4

In [52]:
ar.shape

(5,)

In [53]:
ar2.shape

(2, 2)

In [55]:
ar.dtype

dtype('int32')

In [56]:
ar2.dtype

dtype('int32')

In [59]:
ar22=np.array([(1.4,45,45),(23,45,66)])

In [61]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [62]:
ar22.size

6

In [63]:
range(5)

range(0, 5)

In [64]:
list(range(5))

[0, 1, 2, 3, 4]

In [66]:
list(range(5))

[0, 1, 2, 3, 4]

In [68]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [69]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [70]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [71]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [72]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [79]:
ar4=np.zeros((3,4,2,4))

In [80]:
ar4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [82]:
np.ones(4)

array([1., 1., 1., 1.])

In [84]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [86]:
on=np.ones((2,3,2))

In [87]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [88]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [91]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [93]:
np.eye(4)#identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [94]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [96]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [98]:
arr=np.random.randn(3,4)

In [99]:
import pandas as pd

In [100]:
pd.DataFrame(arr)

0         1         2         3
0  1.054572 -0.985548  0.372456  2.533999
1 -0.974335 -1.250473  0.020852  1.384065
2 -0.497535  0.508652 -0.663952 -0.818436

In [101]:
np.random.rand(3,4)

array([[0.84625706, 0.85854758, 0.57416062, 0.37560789],
       [0.72311375, 0.95416913, 0.92259356, 0.51219407],
       [0.13130885, 0.37077489, 0.65128978, 0.66425423]])

In [108]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv("vikalp.csv")

In [110]:
arr=np.random.rand(3,4)

In [111]:
arr

array([[0.93927158, 0.8257392 , 0.74985768, 0.96007569],
       [0.14467532, 0.25897164, 0.529822  , 0.40588311],
       [0.05333914, 0.73563407, 0.06786917, 0.38153266]])

In [112]:
arr.reshape(6,2)

array([[0.93927158, 0.8257392 ],
       [0.74985768, 0.96007569],
       [0.14467532, 0.25897164],
       [0.529822  , 0.40588311],
       [0.05333914, 0.73563407],
       [0.06786917, 0.38153266]])

In [113]:
arr[1][1]

0.2589716427646067

In [116]:
arr[2:5,1]

array([0.73563407])

In [120]:
arr=np.random.randint(1,100,(5,5))

In [123]:
arr>50

array([[ True, False, False,  True, False],
       [ True,  True,  True, False, False],
       [False, False, False, False, False],
       [ True,  True,  True, False,  True],
       [False,  True, False,  True,  True]])

In [124]:
arr[arr>50]

array([73, 52, 64, 84, 85, 98, 87, 67, 84, 52, 64, 65])

In [125]:
arr

array([[73, 22, 14, 52, 50],
       [64, 84, 85, 41, 23],
       [ 5, 28, 30, 25, 25],
       [98, 87, 67, 48, 84],
       [41, 52,  1, 64, 65]])

In [126]:
arr[2:4,[1,2]]

array([[28, 30],
       [87, 67]])

In [127]:
arr[0][0]=5000

In [128]:
arr

array([[5000,   22,   14,   52,   50],
       [  64,   84,   85,   41,   23],
       [   5,   28,   30,   25,   25],
       [  98,   87,   67,   48,   84],
       [  41,   52,    1,   64,   65]])

In [129]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [130]:
arr1

array([[1, 1, 2],
       [2, 2, 2],
       [1, 2, 1]])

In [131]:
arr2

array([[2, 2, 2],
       [2, 1, 1],
       [2, 1, 1]])

In [132]:
arr1+arr2

array([[3, 3, 4],
       [4, 3, 3],
       [3, 3, 2]])

In [133]:
arr1-arr2

array([[-1, -1,  0],
       [ 0,  1,  1],
       [-1,  1,  0]])

In [134]:
arr1/arr2

array([[0.5, 0.5, 1. ],
       [1. , 2. , 2. ],
       [0.5, 2. , 1. ]])

In [135]:
arr1*arr2

array([[2, 2, 4],
       [4, 2, 2],
       [2, 2, 1]])

In [137]:
arr1@arr2#matrix multiplication

array([[ 8,  5,  5],
       [12,  8,  8],
       [ 8,  5,  5]])

In [138]:
arr1/0

C:\Users\PC\AppData\Local\Temp\ipykernel_3292\1510032488.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [139]:
arr1+100

array([[101, 101, 102],
       [102, 102, 102],
       [101, 102, 101]])

In [140]:
arr1**2

array([[1, 1, 4],
       [4, 4, 4],
       [1, 4, 1]], dtype=int32)

In [142]:
#broadcastinng-Numpy

In [145]:
ar=np.zeros((4,4))

In [146]:
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [147]:
row=np.array([1,2,3,4])

In [148]:
row

array([1, 2, 3, 4])

In [150]:
ar+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [152]:
row.ndim

1

In [153]:
row.T

array([1, 2, 3, 4])

In [154]:
col=np.array([[1,2,3,4]])

In [155]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [157]:
col.T+ar

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [159]:
ar=np.random.randint(1,4,(3,4))

In [160]:
ar

array([[1, 2, 2, 1],
       [1, 1, 3, 2],
       [2, 3, 1, 3]])

In [161]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.41421356, 1.        ],
       [1.        , 1.        , 1.73205081, 1.41421356],
       [1.41421356, 1.73205081, 1.        , 1.73205081]])

In [162]:
np.exp(ar)

array([[ 2.71828183,  7.3890561 ,  7.3890561 ,  2.71828183],
       [ 2.71828183,  2.71828183, 20.08553692,  7.3890561 ],
       [ 7.3890561 , 20.08553692,  2.71828183, 20.08553692]])

In [163]:
np.log10(arr1)

array([[0.     , 0.     , 0.30103],
       [0.30103, 0.30103, 0.30103],
       [0.     , 0.30103, 0.     ]])

In [164]:
#Numpy -Array Manipulation.

In [167]:
arr=np.random.randint(1,20,(3,4))

In [169]:
arr

array([[ 7,  3,  1,  2],
       [ 5, 19,  8, 12],
       [14,  1, 14, 13]])

In [170]:
arr.reshape(2,6)

array([[ 7,  3,  1,  2,  5, 19],
       [ 8, 12, 14,  1, 14, 13]])

In [176]:
arr.reshape(2,-24555)

array([[ 7,  3,  1,  2,  5, 19],
       [ 8, 12, 14,  1, 14, 13]])

In [177]:
arr.T

array([[ 7,  5, 14],
       [ 3, 19,  1],
       [ 1,  8, 14],
       [ 2, 12, 13]])

In [179]:
arr.flatten()#flat the array

array([ 7,  3,  1,  2,  5, 19,  8, 12, 14,  1, 14, 13])

In [180]:
arr1=np.array([1,2,3,3,4])

In [181]:
arr1

array([1, 2, 3, 3, 4])

In [182]:
arr1.ndim

1

In [184]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [185]:
np.squeeze(arr)

array([[ 7,  3,  1,  2],
       [ 5, 19,  8, 12],
       [14,  1, 14, 13]])

In [186]:
data=np.array([[1],[2],[3]])

In [187]:
data

array([[1],
       [2],
       [3]])

In [189]:
np.squeeze(data)#n dim into single dim

array([1, 2, 3])

In [190]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [192]:
np.roll(arr1,2)

array([3, 4, 1, 2, 3])

In [194]:
arr1

array([1, 2, 3, 3, 4])

In [195]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [196]:
#Numpy-Binary Operations

In [200]:
arr1=np.random.randint(1,10,(3,3))

In [201]:
arr1

array([[9, 8, 8],
       [9, 1, 9],
       [5, 3, 7]])

In [202]:
arr2

array([[2, 2, 2],
       [2, 1, 1],
       [2, 1, 1]])

In [203]:
arr1+arr2

array([[11, 10, 10],
       [11,  2, 10],
       [ 7,  4,  8]])

In [204]:
arr1%arr2

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]], dtype=int32)

In [205]:
arr1**arr2

array([[81, 64, 64],
       [81,  1,  9],
       [25,  3,  7]], dtype=int32)

In [206]:
arr1  & arr2

array([[0, 0, 0],
       [0, 1, 1],
       [0, 1, 1]], dtype=int32)

In [207]:
arr1|arr2

array([[11, 10, 10],
       [11,  1,  9],
       [ 7,  3,  7]], dtype=int32)

In [208]:
-arr1

array([[-9, -8, -8],
       [-9, -1, -9],
       [-5, -3, -7]])

In [209]:
arr1>arr2

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True,  True]])

In [210]:
#numpy-String 

In [211]:
arr=np.array(["vikalp","jatin"])

In [212]:
arr

array(['vikalp', 'jatin'], dtype='<U6')

In [213]:
np.char.upper(arr)

array(['VIKALP', 'JATIN'], dtype='<U6')

In [214]:
np.char.title(arr)

array(['Vikalp', 'Jatin'], dtype='<U6')

In [215]:
np.char.capitalize(arr)

array(['Vikalp', 'Jatin'], dtype='<U6')

In [216]:
#Numpy-Mathematical

In [217]:
arr1

array([[9, 8, 8],
       [9, 1, 9],
       [5, 3, 7]])

In [218]:
np.sin(arr1)

array([[ 0.41211849,  0.98935825,  0.98935825],
       [ 0.41211849,  0.84147098,  0.41211849],
       [-0.95892427,  0.14112001,  0.6569866 ]])

In [219]:
np.cos(arr1)

array([[-0.91113026, -0.14550003, -0.14550003],
       [-0.91113026,  0.54030231, -0.91113026],
       [ 0.28366219, -0.9899925 ,  0.75390225]])

In [220]:
np.tan(arr1)

array([[-0.45231566, -6.79971146, -6.79971146],
       [-0.45231566,  1.55740772, -0.45231566],
       [-3.38051501, -0.14254654,  0.87144798]])

In [221]:
np.power(arr1,2)

array([[81, 64, 64],
       [81,  1, 81],
       [25,  9, 49]], dtype=int32)

In [222]:
np.mean(arr1)

6.555555555555555

In [223]:
#sort ,Search,counting function 

In [224]:
arr1=np.array([4,3,4,5,6,7,33,3,5,6,5])

In [225]:
arr1

array([ 4,  3,  4,  5,  6,  7, 33,  3,  5,  6,  5])

In [228]:
np.sort(arr1)

array([ 3,  3,  4,  4,  5,  5,  5,  6,  6,  7, 33])

In [230]:
np.searchsorted(arr1,31)

11

In [231]:
np.count_nonzero(arr1)

11

In [233]:
np.where(arr1>6)

(array([5, 6], dtype=int64),)

In [234]:
np.extract(arr1>6,arr1)

array([ 7, 33])

In [235]:
#Numpy-Byte Swapping

In [236]:
arr1.byteswap()

array([ 67108864,  50331648,  67108864,  83886080, 100663296, 117440512,
       553648128,  50331648,  83886080, 100663296,  83886080])

In [239]:
b=arr1.view()

In [240]:
b

array([ 4,  3,  4,  5,  6,  7, 33,  3,  5,  6,  5])

In [241]:
import numpy.matlib as nm

In [242]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [243]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [244]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [245]:
#Numpy-Linear Algebra

In [246]:
arr1=np.random.randint([[2,3],[4,5]])

In [247]:
arr2=np.random.randint([[3,4],[5,6]])

In [248]:
np.dot(arr1,arr2)

array([[4, 6],
       [0, 2]])